build(nodejs): add support for node18
newrelic/newrelic-lambda-layers pull request #118
Opened 2022-11-22 10:49 UTC by Engerim

aws announced support for nodejs 18, to allow us the upgrade we need to have a nodejs 18 layer

2022-11-22 15:50 UTC, akshaydk approved these changes

2022-11-28 16:37 UTC, mrickard commented
@Engerim Thank you for contributing! We're reviewing this, and we'll keep this issue updated.

2022-11-29 16:37 UTC, mrickard commented on dockerfiles/Dockerfile.nodejs18x
> +RUN ./publish-layers.sh build-nodejs16x
This should be 
`RUN ./publish-layers.sh build-nodejs16x`

2022-11-29 16:37 UTC, mrickard commented on dockerfiles/Dockerfile.nodejs18x
> +CMD ./publish-layers.sh publish-nodejs16x
This should be 
`RUN ./publish-layers.sh build-nodejs18x`

2022-11-29 17:04 UTC, mrickard requested changes
Thank you! Just a couple fixes to the Dockerfile, and we should be good to go.

2022-11-30 08:13 UTC, Engerim commented
@mrickard I have adjusted the two values

2022-11-30 19:16 UTC, mrickard approved these changes
Thank you, @Engerim !

2022-11-30 19:17 UTC, mrickard commented
@Engerim I can take care of the conflicts--I'll just clone your fork.

2022-11-30 19:46 UTC, mrickard commented
@Engerim Thank you again! I've incorporated your changes in this PR, with the conflicts fixed: https://github.com/newrelic/newrelic-lambda-layers/pull/122 (We're removing support for the deprecated Python 3.6 runtime also.)

2022-11-30 19:46 UTC, closed without merging